createOrReplace

	/// Agregacao de reparos reincidentes referenciando a tabela mvp solicitacao_servicos, sem nova consulta ao banco.
	table 'Reparos reincidentes 30d'
		lineageTag: 65b59a75-7025-450e-8bdc-d1912c12632b

		column periodo
			dataType: string
			lineageTag: 49047a1f-8e03-4d55-b1bb-18074c9723e4
			sourceColumn: periodo

		column cidade
			dataType: string
			lineageTag: 94956f92-ec20-4fe8-bf7a-0fce5e0648aa
			sourceColumn: cidade

		column uf
			dataType: string
			lineageTag: c78476ab-581b-4a24-85f8-0e019e4b8ab4
			sourceColumn: uf

		column total_reparos
			dataType: int64
			lineageTag: f8a7f24a-08df-490f-8805-d9c11a8ecbec
			sourceColumn: total_reparos

		column reparos_reincidentes_30d
			dataType: int64
			lineageTag: bcc130a0-200b-4219-944f-5079bbf6f39b
			sourceColumn: reparos_reincidentes_30d

		partition 'Reparos reincidentes 30d' = m
			mode: import
			source =
					let
					    Fonte = #"mvp solicitacao_servicos",
					    Filtrada = Table.SelectRows(
					        Fonte,
					        each [tipo_servico] = "REPARO"
					            and [data_abertura] >= #datetime(2026, 8, 1, 0, 0, 1)
					            and List.Contains({"ENCERRAMENTO", "FINALIZADA", "FECHAMENTO"}, [status])
					    ),
					    Selecionadas = Table.SelectColumns(Filtrada, {"id_contrato", "cidade", "uf", "data_abertura", "data_fechamento"}),
					    Ordenadas = Table.Sort(Selecionadas, {{"id_contrato", Order.Ascending}, {"data_abertura", Order.Ascending}}),
					    PorContrato = Table.Group(
					        Ordenadas,
					        {"id_contrato"},
					        {{
					            "Dados",
					            each
					                let
					                    ComIndice = Table.AddIndexColumn(_, "Indice", 0, 1, Int64.Type),
					                    ComAnterior = Table.AddColumn(
					                        ComIndice,
					                        "data_fechamento_anterior",
					                        each if [Indice] = 0 then null else ComIndice[data_fechamento]{[Indice] - 1},
					                        type nullable datetime
					                    ),
					                    SemIndice = Table.RemoveColumns(ComAnterior, {"Indice"})
					                in
					                    SemIndice,
					            type table [id_contrato=nullable number, cidade=nullable text, uf=nullable text, data_abertura=nullable datetime, data_fechamento=nullable datetime, data_fechamento_anterior=nullable datetime]
					        }}
					    ),
					    Expandida = Table.ExpandTableColumn(
					        PorContrato,
					        "Dados",
					        {"cidade", "uf", "data_abertura", "data_fechamento", "data_fechamento_anterior"},
					        {"cidade", "uf", "data_abertura", "data_fechamento", "data_fechamento_anterior"}
					    ),
					    ComPeriodo = Table.AddColumn(Expandida, "periodo", each Date.ToText(Date.From([data_abertura]), "yyyy-MM"), type text),
					    Agrupada = Table.Group(
					        ComPeriodo,
					        {"periodo", "cidade", "uf"},
					        {
					            {"total_reparos", each Table.RowCount(_), Int64.Type},
					            {
					                "reparos_reincidentes_30d",
					                each Table.RowCount(
					                    Table.SelectRows(
					                        _,
					                        each [data_fechamento_anterior] <> null
					                            and [data_abertura] <> null
					                            and Date.From([data_abertura]) - Date.From([data_fechamento_anterior]) <= #duration(30, 0, 0, 0)
					                    )
					                ),
					                Int64.Type
					            }
					        }
					    ),
					    Resultado = Table.Sort(Agrupada, {{"periodo", Order.Ascending}, {"cidade", Order.Ascending}, {"uf", Order.Ascending}})
					in
					    Resultado

